spring:
  datasource:
    url: jdbc:sqlserver://47.111.144.250:1433;DatebaseName=mixAll
#    url: jdbc:sqlserver://47.106.131.190:1433;DatebaseName=mixAll
#    url: jdbc:sqlserver://222.20.80.142:1433;DatebaseName=mixAll
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: BYzhsw123
#    password: Root123456
#    password: 19960731sxy
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-While-Idle: true
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j,config
  jpa:
    database: sql_server
    ddl-auto: update
#    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
server:
  port: 8089

system:
  #第三方接口
  bigDeviceUrl: http://www.siliancloud.com:8889/
  nbDeviceUrl: http://118.25.217.87/emac_android_connect/

  # 沙箱配置
pay:
  alipay:
    gatewayUrl: https://openapi.alipaydev.com/gateway.do
    #上为支付宝网关,下为appid，均为支付宝给与
    appid: 2016101400682446
    appPrivateKey: MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQCcj+fozvTxWKUjCQtcrgYiPFYXWjMI/hT2t8gKrP/YXUVa9X1l1Nioh9Ob6w8d2B/ma4OrVNz5EnBlhhc/J8TDlgtBDagDVMVuCOW7bp/dVhfgp+gmpGVuUTFvcOGpO39JP/BOjQyVPUTD2O2ZIR/0SlvT1+RK80/nRgOeszEIQVGjBRQ0SvQWYLl4BLh+GmIuOaSNQ0xFTpO73gRaUq677J2lecivzp+rZy53kTdr/dyn7ZANVOQe+blq8lRx9rc/QAW2DdoLA2y3IT6UX6UShWMtuWyf8YJ/8l4ATKryyqDj4wTPe2oXAhB4jsGJPMVWzYExlWqZqlVAZjlJvymFAgMBAAECggEBAJwQFuxK4H90DajO6zSHhDW8T1UX5KeiHuOQbye1K5NR5kC1VTqc4RudyaIyve7R8XqO0cGH5n2hk8if0axyyADvIGjIZCJt7h+xXs9nhpPrrgGTXiam2TUOWmjr7QX0+Pzbb3/duh1J5bIUG0P5cRDizoZtPnQ39f5kHFel58qBOU6PP27YyUPQBtltUXNxB5dpEEjsSNeCk5sDfh4BDQkF0kGLt21zxolh72CQyxM2zgcxoQ8FR31W7CIZqqZ6ku7qE1RFqnFhXahNL3Q5ruUGzI+abBM/+96HM3pK7R4rZjx1FtZ+lZwpk5KIL86nMRORByzrvgTJLZUWO91OUgECgYEA+UIhy7A55Y10JivAkon4kjyrErr8lnBNacAbbbg7L0Ve7uMCrmH5EbmkfpE7SfUSuQgUGgdNE1CxUw/kL+tBhv6WB/zNfUYWsGyAqO8odGTo4ruqMDNETzyddm0o/dhYqtObBGMhtk6ovW8hAShdwRtg6UVJqRHpWETXRleQzD0CgYEAoMvxtj8g0zwk5mZVKOXDqGj+9XE7Sso8/3ujZCeUyjk4/qwG5ipNe2WIR68o7UK+3mmdvT8/9+txrmyWlqNHLXTnbWWjboxS8Es2N3dIu8/ytOZGrcsd37Dq32sErIDcqFlH/R4Ur5o0pYBSl/kzyWDY5S0dgQLNxP/OlbLgvukCgYEAnn7v0H6hghc9eRwvGr9C4XJUcdeWz+5fO1Rd3JnegIODBzIwvUQtRZkfQSAGbFO68Q9zAM4Ns6+G4kNjnRjiFP4D1tZosDUGLm8ALOvOdJzJ/YrJgFbJI/1uPyTQgQG1+AIQO2zxveQspjBo8zyAyU8og4x8d1adY3R60w7RUx0CgYEAiqYQb/MTHNFZiAlpGPC1uzt9zKmsVJr56dn0U2IF3DFnQcGX2VNUqDguQJF6msrYxfMP/qTRRbcQuTQMzStRLpMFEsF3INWCloxj3YPPhZKTVwTQoP7pbX6hp7AhwZUDr238svcDIz+2cZaqoTxSOSx3GXXDYQDH6TwiJ9asEDECgYEAtBychp0uU3X1BzgMkJDO4TQRHZIpJdTS5bbbQCRqjYx3MwrYihj2pk19E/MGW6biIW0J2Kw5JGzgjXuxwigEHDQC1cO4CGg23xMIxfazgT4OEJDbT7AROsXnazXsTxAvbuINEB30nb+Hso1tJ0l3VZ2Gv/h4Mf59ITfiTfhxVeA=
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnI/n6M708VilIwkLXK4GIjxWF1ozCP4U9rfICqz/2F1FWvV9ZdTYqIfTm+sPHdgf5muDq1Tc+RJwZYYXPyfEw5YLQQ2oA1TFbgjlu26f3VYX4KfoJqRlblExb3DhqTt/ST/wTo0MlT1Ew9jtmSEf9Epb09fkSvNP50YDnrMxCEFRowUUNEr0FmC5eAS4fhpiLjmkjUNMRU6Tu94EWlKuu+ydpXnIr86fq2cud5E3a/3cp+2QDVTkHvm5avJUcfa3P0AFtg3aCwNstyE+lF+lEoVjLblsn/GCf/JeAEyq8sqg4+MEz3tqFwIQeI7BiTzFVs2BMZVqmapVQGY5Sb8phQIDAQAB
#    returnUrl: http://fuzsmc.natappfree.cc/alipay/return
    notifyUrl: http://127.0.0.1:8089/alipay/getNotify

